GET http://localhost:8080/api/v1/degree
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI0Njg3MzUsInVzZXJJZCI6MTAwfQ.MU8q2NkqCgtGMxQGHggcuBR8J9tlSSCNQBJa7q3CTsk

###
GET http://localhost:8080/api/v1/degree/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI0Njg3MzUsInVzZXJJZCI6MTAwfQ.MU8q2NkqCgtGMxQGHggcuBR8J9tlSSCNQBJa7q3CTsk

###
POST http://localhost:8080/api/v1/degree
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI0Njg3MzUsInVzZXJJZCI6MTAwfQ.MU8q2NkqCgtGMxQGHggcuBR8J9tlSSCNQBJa7q3CTsk

{
  "code": "0000",
  "response": [{
    "degree": 1,
    "name": "Administración de empresas"
  },
    {
      "degree": 2,
      "name": "Administración turística"
    },
    {
      "degree": 3,
      "name": "Contaduría pública"
    },
    {
      "degree": 4,
      "name": "Economía"
    },
    {
      "degree": 5,
      "name": "Economía e Inteligencia de negocios"
    },
    {
      "degree": 6,
      "name": "Ingeniería en innovación empresarial"
    },
    {
      "degree": 7,
      "name": "Ingeniería comercial"
    },
    {
      "degree": 8,
      "name": "Marketing y medios digitales"
    },
    {
      "degree": 9,
      "name": "Ingeniería ambiental"
    },
    {
      "degree": 10,
      "name": "Ingeniería biomédica"
    },
    {
      "degree": 11,
      "name": "Ingeniería bioquímica y de bioprocesos"
    },
    {
      "degree": 12,
      "name": "Ingeniería civil"
    },
    {
      "degree": 13,
      "name": "Ingeniería en energía"
    },
    {
      "degree": 14,
      "name": "Ingeniería en logística y analítica de la cadena de suministro"
    },
    {
      "degree": 15,
      "name": "Ingeniería en multimedia e interactividad digital"
    },
    {
      "degree": 16,
      "name": "Ingeniería industrial"
    },
    {
      "degree": 17,
      "name": "Ingeniería química"
    },
    {
      "degree": 18,
      "name": "Ingeniería mecatrónica"
    },
    {
      "degree": 19,
      "name": "Ingeniería en sistemas"
    },
    {
      "degree": 20,
      "name": "Ingeniería de telecomunicaciones"
    },
    {
      "degree": 21,
      "name": "Comunicación social"
    },
    {
      "degree": 22,
      "name": "Filosofía y letras"
    },
    {
      "degree": 23,
      "name": "Psicología"
    },
    {
      "degree": 24,
      "name": "Psicopedagogía"
    },
    {
      "degree": 25,
      "name": "Arquitectura"
    },
    {
      "degree": 26,
      "name": "Arquitectura de interiores"
    },
    {
      "degree": 27,
      "name": "Diseño digital"
    },
    {
      "degree": 28,
      "name": "Diseño gráfico y comunicación visual"
    },
    {
      "degree": 29,
      "name": "Ciencias Políticas y relaciones internacionales"
    },
    {
      "degree": 30,
      "name": "Derecho"
    }
  ],
  "errorMessage": null
}

###
PUT http://localhost:8080/api/v1/degree/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI0Njg3MzUsInVzZXJJZCI6MTAwfQ.MU8q2NkqCgtGMxQGHggcuBR8J9tlSSCNQBJa7q3CTsk

{
  "name": "Etiqueta actualizada"
}
